# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 14:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_accounts', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bucketlist',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth_accounts.Base')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name',),
            },
            bases=('auth_accounts.base',),
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth_accounts.Base')),
                ('name', models.CharField(max_length=128)),
                ('done', models.BooleanField(default=False)),
                ('bucketlist_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bucketlist_id', to='bucketlist.Bucketlist')),
            ],
            options={
                'ordering': ('name',),
            },
            bases=('auth_accounts.base',),
        ),
    ]
