# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='base',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='base',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
